### ISSUE TITLE
Add back in aggregates

### ISSUE THREAD

**Issue by doug-shontz** [WithOneVisionTechnologies/omnihive-server#13]
Need to investigate how to add back in Kaleb's aggregate stuff so that dashboarding is easier in the EC.

**Comment by doug-shontz** [comment]
@zapbampow @Jayrene1 Assigning this to @KalebMatthews  to work on.

**Comment by KalebMatthews** [comment]
This is now in Beta and free to be used there. Keep issue open until testing is complete.

**Comment by doug-shontz** [comment]
Closing this out as it went into production with the notification bell stuff.  Will open another ticket if it is a bug that is found.
