### ISSUE TITLE
Error: cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Jayrene1** [WithOneVisionTechnologies/omnihive-server#5]
When running .init() on the omnihive-client, initialization fails with "Error: cannot read property 'split' of undefined". Running the function again will successfully initialize the client. This issue is apparently related to replacing an expired token.

**Comment by Jayrene1** [comment]
When running .init() on the omnihive-client, initialization fails with "Error: cannot read property 'split' of undefined".  Running the function again will successfully initialize the client. This issue is apparently related to replacing an expired token.

**Comment by doug-shontz** [comment]
The initial init with a new token was not returning the client ID appended to the token packet but WAS storing it in the database correctly, which means all subsequent calls were fine.
