### ISSUE TITLE
Documentation: Developer Settings

### ISSUE THREAD

**Issue by KalebMatthews** [WithOneVisionTechnologies/omnihive-server#8]
The changes that need to be made in the config file to get developer settings to happen properly. i.e. debug points.

**Comment by doug-shontz** [comment]
Also add to turn on node:auto attach in VS Code or debug points won't work.

**Comment by doug-shontz** [comment]
Now that this has settled down I have updated the CUSTOM_FUNCTION_DEVELOPMENT.md.  Will be checked in the next time I push.
